spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/organization
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    serialization.FAIL_ON_EMPTY_BEANS: false

user-group:
  service: http://localhost:8085

server:
  port: 8081
