spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/permission
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    serialization.FAIL_ON_EMPTY_BEANS: false

server:
  port: 8082
